### ISSUE TITLE
Not working with NextJS 14.2.15

### ISSUE THREAD

**Issue by minhchi1509** [MrBr/antd-zod#14]
It seems that the error message does not display.
My repo: https://stackblitz.com/edit/stackblitz-starters-qftcjv

**Comment by MrBr** [comment]
Can't get example running. Please check it out.

![image](https://github.com/user-attachments/assets/92ebf489-6b29-4dba-bf73-3013d42285b8)

**Comment by MrBr** [comment]
I'm trying on stackblitz and getting this

![Screenshot 2024-11-21 at 09 20 21](https://github.com/user-attachments/assets/c965eb17-9b3c-4ca1-8e0c-f03a5aa72b1d)

**Comment by minhchi1509** [comment]
I have created another repo and used Vite instead of NextJS. Please check it. When I click on submit button, the error message does not display properly, but when I fill in the value in the field and then delete it, the error message appears.
https://stackblitz.com/edit/vitejs-vite-bnvr4i?file=src%2FApp.tsx

**Comment by minhchi1509** [comment]
Hello. is there any update???

**Comment by MrBr** [comment]
After looking at it more carefully I figured out it's because of Zod nature of validation. When validating with coerce flag on, validation will force any given value to wanted primitive as per [documentation](https://zod.dev/?id=coercion-for-primitives).

That means when an input is empty, the value that Zod gets in validation is `undefined` and since it's being coerced to primitive, it validates "undefined" which passes your schema.

In this case, you shouldn't be using coerce in schema. Schema should expect strict types. Form input should take care that the given value has the right type. Look at Zod schema here strictly as a validation tool, not (data) transformation.
